security:
    encoders:
        Common\UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_EDITOR:    ROLE_USER
        ROLE_ADMIN:       [ROLE_EDITOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_EDITOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        blog_users:
            entity:
                class: CommonUserBundle:User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        blog_security:
            switch_user: true
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: _check_path
                login_path: blog_login
                default_target_path: blog_index
              #  username_parameter: login[_username]
              #  password_parameter: login[_password]
            logout:
                path:   _logout
                target: blog_index
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
                remember_me_parameter: login[remember_me]
            #
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/account-settings, roles: ROLE_USER }
        - { path: ^/admin-panel, roles: ROLE_EDITOR }